print('gamarjoba')
print('aleqsandre')
print('mefarishvili')
print(14)
print('shaurma')
print('GOA')
print('first')
print('MMA')
print('february')
print('Homework')
print('100')
print('luka')
print('andria')
print('davit')
Country= "georgia"
print('country')
print('Tbilisi')
print('777')
number = 77
print('number')
print(18909893794)
print('demetre')